"""Generate the self-contained input decks of the paper cases from one base deck.
All cases are the PWFA ion-motion setup of examples/pwfa_ion_motion.in with the
overrides listed below; run once after changing the base: python3 make_decks.py"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "..", "..", "examples", "pwfa_ion_motion.in")


def stretched(s):
    return "0.05:%g  2.5:%g  8.0:%g" % (0.0005 * s, 0.01 * s, 0.05 * s)


SINGLE = {"time.steps": "0", "xi.max": "7.3", "driver.analytic": "1", "witness.analytic": "1"}
EVO = {"output.every": "0", "output.beam_every": "0", "driver.analytic": "1"}

cases = {}   # name -> (comment, overrides)
for dr in ["0.02", "0.01", "0.005", "0.0025", "0.00125"]:
    cases["conv_u" + dr] = ("Fig. conv / Table: single field solve, uniform grid dr = " + dr,
                            dict(SINGLE, **{"grid.type": "uniform", "grid.dr": dr}))
for s in ["4", "2", "1", "0.5", "0.25", "0.125", "0.0625"]:
    cases["conv_s" + s] = ("Fig. conv / Table: single field solve, stretched grid, steps x " + s,
                           dict(SINGLE, **{"grid.regions": stretched(float(s))}))
cases["conv_ref_s0.03125"] = ("Fig. conv: reference solution (stretched, steps x 1/32, N = 14617)",
                              dict(SINGLE, **{"grid.regions": stretched(0.03125)}))
cases["conv_ref_u0.00025"] = ("Fig. conv: uniform cross-check of the reference (N = 32000; large memory)",
                              dict(SINGLE, **{"grid.type": "uniform", "grid.dr": "0.00025"}))
cases["maps_s1"] = ("Fig. maps: full box xi = 0..9, stretched grid of the base deck",
                    {"time.steps": "0", "driver.analytic": "1", "witness.analytic": "1"})
cases["evo_s1"] = ("Fig. evo: 100 steps, analytic driver, particle witness, stretched x 1", dict(EVO))
cases["evo_s0.5"] = ("Fig. evo: 100 steps, stretched x 0.5",
                     dict(EVO, **{"grid.regions": stretched(0.5)}))
cases["evo_u0.01"] = ("Fig. evo: 100 steps, uniform dr = 0.01",
                      dict(EVO, **{"grid.type": "uniform", "grid.dr": "0.01"}))
cases["evo_u0.005"] = ("Fig. evo: 100 steps, uniform dr = 0.005",
                       dict(EVO, **{"grid.type": "uniform", "grid.dr": "0.005"}))
cases["bench_particles_s1"] = ("GPU benchmark (not in the paper): base deck as is, both beams as "
                               "particles (6e5), 100 steps", {})

base = open(BASE).read().splitlines()
for name, (comment, ov) in cases.items():
    ov = dict(ov, **{"output.dir": "out_" + name})
    out, seen = ["# QUARZ paper case '%s' -- generated by make_decks.py from examples/pwfa_ion_motion.in" % name,
                 "# " + comment], set()
    for line in base:
        key = line.split("=")[0].strip() if "=" in line and not line.lstrip().startswith("#") else None
        if key in ov:
            out.append("%-16s = %s      # paper case" % (key, ov[key]))
            seen.add(key)
        elif key in ("grid.regions", "grid.max_ratio") and ov.get("grid.type") == "uniform":
            out.append("# " + line + "      (unused: uniform grid)")
        else:
            out.append(line)
    extra = [k for k in ov if k not in seen]
    if extra:
        out.append("")
        out.append("# paper-case settings")
        out += ["%-16s = %s" % (k, ov[k]) for k in extra]
    open(os.path.join(HERE, name + ".in"), "w").write("\n".join(out) + "\n")
print("wrote %d decks" % len(cases))
